development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

#dummy to get assets:precompile to work
#see http://devcenter.heroku.com/articles/rails31_heroku_cedar
production:
  adapter: postgresql
  database: crambear_production
  username: postgres
  password: pwwwwww23
