development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

#dummy to get assets:precompile to work
#see http://devcenter.heroku.com/articles/rails31_heroku_cedar
production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: dc5cfd0gd8l5hu
  username: mctqpybmccghgi
  password: NSt8DGmTjboatGGMPT2KuXVoZK
  host: ec2-54-227-252-82.compute-1.amazonaws.com
  port: 5432


